// Prevod tipa izdelka (npr. »Moške kopalne hlače · BOARDSHORT · 4 WAYS STRETCH«) za prikaz v HR/EN.
// Tip ostane v bazi slovenski (uporablja se za razvrščanje) — prevaja se samo prikaz.
const SEG = {
  "Moške kopalne hlače": ["Muške kupaće hlače", "Men's swim shorts"],
  "Moško spodnje perilo": ["Muško donje rublje", "Men's underwear"],
  "Moška majica": ["Muška majica", "Men's T-shirt"],
  "Moška brezrokavna majica": ["Muška majica bez rukava", "Men's tank top"],
  "Moška polo majica": ["Muška polo majica", "Men's polo shirt"],
  "Moška kopalna majica": ["Muška kupaća majica", "Men's swim shirt"],
  "Moška jopa": ["Muška dukserica", "Men's hoodie"],
  "Moška jopica": ["Muška jaknica", "Men's jacket"],
  "Moška srajca": ["Muška košulja", "Men's shirt"],
  "Moške japonke": ["Muške japanke", "Men's flip-flops"],
  "Moške kratke hlače": ["Muške kratke hlače", "Men's shorts"],
  "Moške športne kratke hlače 2 v 1": ["Muške sportske kratke hlače 2 u 1", "Men's 2-in-1 sport shorts"],
  "Moški natikači": ["Muške natikače", "Men's slides"],
  "Moški pulover": ["Muški pulover", "Men's sweater"],
  "Moški vindstoper": ["Muška vjetrovka", "Men's windbreaker"],
  "Ženska jopa": ["Ženska dukserica", "Women's hoodie"],
  "Ženska jopica": ["Ženska jaknica", "Women's jacket"],
  "Ženska kiklica": ["Ženska suknjica", "Women's skirt"],
  "Ženska kopalna majica": ["Ženska kupaća majica", "Women's swim shirt"],
  "Ženska majica": ["Ženska majica", "Women's T-shirt"],
  "Ženska oblekica": ["Ženska haljinica", "Women's dress"],
  "Ženska spodnja majica": ["Ženska potkošulja", "Women's undershirt"],
  "Ženske japonke": ["Ženske japanke", "Women's flip-flops"],
  "Ženske kopalke": ["Ženski kupaći kostim", "Women's swimwear"],
  "Ženske kopalne hlače": ["Ženske kupaće hlače", "Women's swim shorts"],
  "Ženske kratke hlače": ["Ženske kratke hlače", "Women's shorts"],
  "Ženske pajkice": ["Ženske tajice", "Women's leggings"],
  "Ženski športni modrček": ["Ženski sportski grudnjak", "Women's sports bra"],
  "Ženska športna majica brez rokavov": ["Ženska sportska majica bez rukava", "Women's sports tank top"],
  "Ženski top s košaricami": ["Ženski top s košaricama", "Women's cup top"],
  "Ženski kimono": ["Ženski kimono", "Women's kimono"],
  "Žensko spodnje perilo": ["Žensko donje rublje", "Women's underwear"],
  "Otroška jopa": ["Dječja dukserica", "Kids' hoodie"],
  "Otroška kopalna majica": ["Dječja kupaća majica", "Kids' swim shirt"],
  "Otroška majica": ["Dječja majica", "Kids' T-shirt"],
  "Otroške kopalne hlače": ["Dječje kupaće hlače", "Kids' swim shorts"],
  "Otroško spodnje perilo": ["Dječje donje rublje", "Kids' underwear"],
  "Unisex kapa z ravnim šiltom": ["Unisex kapa s ravnim šiltom", "Unisex flat-brim cap"],
  "Unisex kapa z ukrivljenim šiltom": ["Unisex kapa sa zakrivljenim šiltom", "Unisex curved-brim cap"],
  "Nogavice": ["Čarape", "Socks"],
  "Dodatki": ["Dodaci", "Accessories"],
  "MIKROFIBRA": ["MIKROFIBRA", "MICROFIBRE"],
  "BAMBUS": ["BAMBUS", "BAMBOO"],
  "BREZ ROKAV": ["BEZ RUKAVA", "SLEEVELESS"],
  "DOLGI ROKAV": ["DUGI RUKAV", "LONG SLEEVE"],
  "KRATKI ROKAV": ["KRATKI RUKAV", "SHORT SLEEVE"],
  "S KAPUCO": ["S KAPULJAČOM", "HOODED"],
  "SPODNJI DEL": ["DONJI DIO", "BOTTOM"],
  "ZGORNJI DEL": ["GORNJI DIO", "TOP"],
  "ŠIROKE": ["ŠIROKE", "WIDE"],
};
export function typeLabel(type, lang) {
  if (!type || lang === "sl") return type || "";
  const i = lang === "en" ? 1 : 0;
  return type.split(" · ").map((s) => (SEG[s.trim()] ? SEG[s.trim()][i] : s)).join(" · ");
}
